IF not EXISTS (
     SELECT name FROM master.dbo.sysdatabases 
    WHERE name = N'QL_THIETBI'
)
	begin
		create database QL_THIETBI
	end
GO
use QL_THIETBI
GO
CREATE TABLE LOAITB
(
	MALOAI INT Identity(1,1) NOT NULL PRIMARY KEY,
	TENLOAI NVARCHAR(100)
)
CREATE TABLE NHACC
(
	MANCC int Identity(1,1) NOT NULL PRIMARY KEY,
	TENNCC NVARCHAR(100),
	SDT NVARCHAR(15),
	DIACHI NVARCHAR(100)
)
CREATE TABLE THIETBI
(
	MATB int Identity(1,1) NOT NULL PRIMARY KEY,
	TENTB NVARCHAR(1000),
	HINHANH NVARCHAR(150),
	GIA MONEY,
	SOLUONG INT,
	MOTA NVARCHAR(1000),
	MALOAI INT,
	MANCC INT,
	TINHTRANG NVARCHAR(130),
	CONSTRAINT FK_THIETBI_NHACC FOREIGN KEY(MANCC) REFERENCES NHACC(MANCC),
	CONSTRAINT FK_THIETBI_LOAITB FOREIGN KEY(MALOAI) REFERENCES LOAITB(MALOAI)
)
CREATE TABLE QUYEN
(
	MAQUYEN int Identity(1,1) NOT NULL PRIMARY KEY,
	TENQUYEN NVARCHAR(30)
)
CREATE TABLE NHANVIEN
(
	MANV int Identity(1,1) NOT NULL PRIMARY KEY,
	TENNV NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(4),
	SDT NVARCHAR(15),
	DIACHI NVARCHAR(100),
	MATKHAU NVARCHAR(1000),
	MAQUYEN int,
	CONSTRAINT FK_NHANVIEN_QUYEN FOREIGN KEY(MAQUYEN) REFERENCES QUYEN(MAQUYEN)
	
)
CREATE TABLE KHACHHANG
(
	MAKH int Identity(1,1) NOT NULL PRIMARY KEY,
	TENKH NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(4),
	SDT NVARCHAR(15),
	DIACHI NVARCHAR(100),
	
)
CREATE TABLE DONNHAP
(
	MADN int Identity(1,1) NOT NULL PRIMARY KEY,
	MANV INT,
	MANCC INT,
	NGAYLAP DATE,
	TONGTIEN MONEY,
	GHICHU NVARCHAR(1000),
	CONSTRAINT FK_DONNHAP_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	CONSTRAINT FK_DONNHAP_NHACC FOREIGN KEY(MANCC) REFERENCES NHACC(MANCC)
)
CREATE TABLE CHITIETDN
(
	MADN int NOT NULL,
	MATB INT NOT NULL,
	SOLUONG INT,
	GIANHAP MONEY,
	THANHTIEN MONEY,
	CONSTRAINT PK_CHITIETDN PRIMARY KEY(MADN,MATB),
	CONSTRAINT FK_CHITIETDN_DONNHAP FOREIGN KEY(MADN) REFERENCES DONNHAP(MADN),
	CONSTRAINT FK_CHITIETDN_THIETBI FOREIGN KEY(MATB) REFERENCES THIETBI(MATB)
)
CREATE TABLE DONHANG
(
	MADH int Identity(1,1) NOT NULL PRIMARY KEY,
	MAKH INT,
	MANV INT,
	NGAYLAP DATE,
	TONGTIEN MONEY,
	HINHTHUCTT NVARCHAR(50),
	TINHTRANG NVARCHAR(100),
	GHICHU NVARCHAR(1000),
	CONSTRAINT FK_DONHANG_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_DONHANG_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

)
CREATE TABLE CHITIETDH
(
	MADH int NOT NULL,
	MATB INT NOT NULL,
	SOLUONG INT,
	GIABAN MONEY,
	THANHTIEN MONEY,
	CONSTRAINT PK_CHITIETDH PRIMARY KEY(MADH,MATB),
	CONSTRAINT FK_CHITIETDH_THIETBI FOREIGN KEY(MATB) REFERENCES THIETBI(MATB),
	CONSTRAINT FK_CHITIETDH_DONHANG FOREIGN KEY(MADH) REFERENCES DONHANG(MADH)
)
insert into LOAITB(TENLOAI)
VALUES(N'ÐIỆN THOẠI'),
 (N'LAPTOP'),
 (N'TIVI'),
 (N'MÁY GIẶT'),
 (N'TỦ LẠNH'),
 (N'PHỤ KIỆN')

 INSERT INTO NHACC(TENNCC,SDT,DIACHI)
 VALUES(N'SAMSUNG',N'090987293',N'TPHCM'),
 (N'ACER',N'0909879879',N'TPHCM'),
 (N'VINSMART',N'09067879',N'Hà Nội')

 INSERT INTO THIETBI(TENTB,HINHANH ,GIA,SOLUONG,MOTA,MALOAI,MANCC,TINHTRANG)
 values('Samsung Galaxy A52','hinh1.jpg',9990000,32,N'Chiếc điện thoại sở hữu màn hình Infinity-O đầy hiện đại, 
 4 máy ảnh mặt sau được sắp xếp gọn gàng bên trong mô-đun hình chữ nhật thân thuộc và
  các cạnh viền bo cong nhẹ nhàng, uyển chuyển quanh thân máy, tạo cảm giác dễ chịu khi cầm nắm sử dụng.',1,1,N'NEW'),

  ('Laptop Acer Nitro 5 Gaming AN515 57 727J i7 11800H/8GB/512GB/4GB RTX3050Ti/144Hz/Win10 (NH.QD9SV.005.)','hinh2.jpg',26990000,31,N'Acer Nitro 
  Gaming được trang bị bộ vi xử lý Intel Core i7 Tiger Lake với cấu trúc 8 nhân 16 luồng có tốc độ đạt tối đa đến 4.6 GHz nhờ Turbo Boost cho máy
   hiệu năng mạnh mẽ chạy tốt các tựa game cấu hình cao, xử lý các tác vụ đồ họa chuyên nghiệp một cách trơn tru.
RAM 8 GB chuẩn DDR4 2 khe (1 khe 8 GB + 1 khe rời) cùng khả năng nâng cấp tối đa lên đến 32 GB xử lý đa nhiệm cùng 
lúc nhiều tác vụ, việc di chuyển qua lại giữa các phần mềm, chạy đồng thời các ứng dụng đồ họa mà không lo 
 tượng giật, lag.',2,1,N'NEW'),


 ('Vsmart Star 3','hinh3.jpg',1990000,12,N'Chiếc điện thoại Vsmart Star 3 được trang bị bộ đôi camera kép ở mặt lưng bao gồm một 
 camera chính độ phân giải 8 MP và một camera góc siêu rộng 5 MP.',1,3,N'NEW'),


 ('Điện thoại Vsmart Aris (8GB/128GB)','hinh4.jpg',3990000,12,N'CPhần thiết kế của Vsmart Aris có độ hoàn thiện cao với phần khung
  viền kim loại và mặt lưng là một lớp kính phủ nhám tốt giúp chống bám mồ hôi, dấu vân tay hiệu quả.Mặt kính Corning Gorilla Glass 5 phủ hoàn 
  toàn trên bề mặt của thiết bị mang lại sự an toàn bền bỉ lẫn nét sang trọng, cao cấp cho máy.',1,3,N'NEW')


  INSERT INTO QUYEN(TENQUYEN)
  VALUES(N'Quản Lí'),
  (N'Bán Hàng'),
  (N'Bảo Trì'),
  (N'Kế Toán')

  SET DATEFORMAT DMY
  INSERT INTO NHANVIEN(TENNV,NGAYSINH,GIOITINH,SDT,DIACHI ,MATKHAU ,MAQUYEN)
  VALUES
  (N'Văn Hường', N'16/01/2001', N'Nam', N'0999999999', N'Tây Ninh', N'C8C605999F3D8352D7BB792CF3FDB25B', 1),--MK:999999999
  (N'Nguyên Khang', N'22/04/2000', N'Nữ', N'0911911911', N'Bến Tre', N'C8C605999F3D8352D7BB792CF3FDB25B', 1)--MK:999999999

INSERT INTO KHACHHANG(TENKH,NGAYSINH,GIOITINH,SDT,DIACHI )
VALUES(N'Nguyễn Nguyên Bảo',N'22/02/2001',N'Nam','08329023',N'TPHCM'),
(N'Nguyễn Thanh Loan',N'22/02/2001',N'Nữ','083294533',N'Hà Nội'),
(N'Nguyễn Thanh Bình',N'22/02/2001',N'Nữ','083294533',N'Hà Nội')

INSERT INTO DONNHAP(MANV ,MANCC,NGAYLAP,TONGTIEN ,GHICHU )
VALUES(1,1,N'23/09/2020',3000000,N''),
(1,2,N'23/09/2020',400000,N''),
(1,1,N'24/09/2020',3000000,N'')


INSERT INTO CHITIETDN(MADN,MATB,SOLUONG,GIANHAP,THANHTIEN)
VALUES(1,1,3,500000,1500000),
(1,2,3,500000,1500000),
(2,1,3,500000,1500000),
(2,2,3,500000,1500000),
(2,3,2,500000,1000000),
(3,2,2,1500000,3000000)

INSERT INTO DONHANG(MAKH,MANV ,NGAYLAP,TONGTIEN ,HINHTHUCTT,TINHTRANG,GHICHU )
VALUES(1,1,'22/02/2021',12300000,N'TRẢ GÓP',N'HOÀN THÀNH',N''),
(2,1,'22/02/2021',12300000,N'ĐÃ THANH TOÁN',N'HOÀN THÀNH',N''),
(1,2,'23/02/2021',1200000,N'ĐÃ THANH TOÁN',N'HOÀN THÀNH',N'')

INSERT INTO CHITIETDH(MADH ,MATB ,SOLUONG ,GIABAN ,THANHTIEN )
VALUES(1,1,3,500000,1500000),
(1,2,3,500000,1500000),
(2,1,3,500000,1500000),
(2,2,3,500000,1500000),
(2,3,2,500000,1000000),
(3,2,2,1500000,3000000)


---Mỗi khi thêm, xóa, sửa vào bảng CHITIETDH sẽ cập nhật thành tiền ở CHITIETDH , tổng tiền ở DONHANG
GO
CREATE TRIGGER TINHTHANHTIEN ON CHITIETDH
FOR INSERT,DELETE,UPDATE
AS
	DECLARE @madh int,@matb int	,@thanhtien money,@tongtien money
	if(select count(*) from inserted)>0
		BEGIN
		set @madh=(select MADH FROM inserted)
		set @matb=(select MATB FROM inserted)
		
		END
	ELSE
		BEGIN
		set @madh=(select MADH FROM deleted)
		set @matb=(select MATB FROM deleted)
		
		END

	SET @tongtien=(select sum(GIABAN*SOLUONG) FROM DONHANG,CHITIETDH WHERE DONHANG.MADH=CHITIETDH.MADH AND DONHANG.MADH=@madh GROUP BY DONHANG.MADH)
	set @thanhtien=(select GIABAN*SOLUONG FROM CHITIETDH WHERE  MADH=@madh and MATB=@matb)
	
	update CHITIETDH
	set THANHTIEN=@thanhtien
	where MADH=@madh and MATB=@matb

	update DONHANG
	set TONGTIEN=@tongtien
	where MADH=@madh
INSERT INTO CHITIETDH(MADH ,MATB ,SOLUONG ,GIABAN )
VALUES(2,4,2,500000)
DELETE FROM CHITIETDH WHERE MADH=2 and MATB =2

---Mỗi khi thêm, xóa, sửa vào bảng CHITIETDN sẽ cập nhật thành tiền ở CHITIETDH , tổng tiền ở DONNHAP
GO
CREATE TRIGGER TINHTIENNHAP ON CHITIETDN
FOR INSERT,DELETE,UPDATE
AS
	DECLARE @madh int,@matb int	,@thanhtien money,@tongtien money
	if(select count(*) from inserted)>0
		BEGIN
		set @madh=(select MADN FROM inserted)
		set @matb=(select MATB FROM inserted)
		
		END
	ELSE
		BEGIN
		set @madh=(select MADN FROM deleted)
		set @matb=(select MATB FROM deleted)
		
		END

	SET @tongtien=(select sum(GIANHAP*SOLUONG) FROM DONNHAP,CHITIETDN WHERE DONNHAP.MADN=CHITIETDN.MADN AND DONNHAP.MADN=@madh GROUP BY DONNHAP.MADN)
	set @thanhtien=(select GIANHAP*SOLUONG FROM CHITIETDN WHERE  MADN=@madh and MATB=@matb)
	
	update CHITIETDN
	set THANHTIEN=@thanhtien
	where MADN=@madh and MATB=@matb

	update DONNHAP
	set TONGTIEN=@tongtien
	where MADN=@madh
INSERT INTO CHITIETDN(MADN ,MATB ,SOLUONG ,GIANHAP)
VALUES(2,4,2,500000)
DELETE FROM CHITIETDN WHERE MADN=2 and MATB =2
SELECT*FROM THIETBI
SELECT*FROM LOAITB
SELECT*FROM NHACC
SELECT*FROM KHACHHANG
SELECT*FROM NHANVIEN
SELECT*FROM QUYEN
SELECT*FROM DONHANG
SELECT*FROM CHITIETDH
SELECT*FROM DONNHAP
SELECT*FROM CHITIETDN

--tạo view sản phẩm
go
create view SANPHAM
AS
SELECT MATB,TENTB,GIA,SOLUONG,MOTA,TENLOAI,TENNCC,TINHTRANG
FROM THIETBI,LOAITB,NHACC
WHERE THIETBI.MALOAI=LOAITB.MALOAI AND NHACC.MANCC=THIETBI.MANCC
go----------------------
SELECT*FROM SANPHAM
------ko chạy
BACKUP DATABASE QL_THIETBI TO DISK = N'D:\LVH\abc.bak'
EXEC xp_dirtree 'D:\LVH',1,1
Use master; ALTER DATABASE QL_THIETBI SET SINGLE_USER WITH ROLLBACK IMMEDIATE
Use master; RESTORE DATABASE QL_THIETBI FROM DISK = 'D:\LVH\abc.bak' WITH REPLACE
Use master; ALTER DATABASE QL_THIETBI SET MULTI_USER WITH ROLLBACK IMMEDIATE