<?xml version="1.0" encoding="utf-8"?><Database Name="QL_THIETBI" Class="QL_LinhKienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-QDRGJQ8\SQLEXPRESS;Initial Catalog=QL_THIETBI;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_THIETBIConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BAOCAO" Member="BAOCAOs">
    <Type Name="BAOCAO">
      <Column Name="MABC" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYLAPBC" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MANV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NHANVIEN_BAOCAO" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THIETBI" Member="THIETBIs">
    <Type Name="THIETBI">
      <Column Name="MATB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENTB" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="HINHANH" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="MALOAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="THIETBI_CTDONHANG" Member="CTDONHANGs" ThisKey="MATB" OtherKey="MATB" Type="CTDONHANG" />
      <Association Name="THIETBI_CTDONHAP" Member="CTDONHAPs" ThisKey="MATB" OtherKey="MATB" Type="CTDONHAP" />
      <Association Name="LOAITB_THIETBI" Member="LOAITB" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAITB" IsForeignKey="true" />
      <Association Name="NHACC_THIETBI" Member="NHACC" ThisKey="MANCC" OtherKey="MANCC" Type="NHACC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.COSO" Member="COSOs">
    <Type Name="COSO">
      <Column Name="MACS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENCS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="COSO_DONNHAP" Member="DONNHAPs" ThisKey="MACS" OtherKey="MACS" Type="DONNHAP" />
    </Type>
  </Table>
  <Table Name="dbo.CTDONHANG" Member="CTDONHANGs">
    <Type Name="CTDONHANG">
      <Column Name="MADH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATB" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="THIETBI_CTDONHANG" Member="THIETBI" ThisKey="MATB" OtherKey="MATB" Type="THIETBI" IsForeignKey="true" />
      <Association Name="DONHANG_CTDONHANG" Member="DONHANG" ThisKey="MADH" OtherKey="MADH" Type="DONHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTDONHAP" Member="CTDONHAPs">
    <Type Name="CTDONHAP">
      <Column Name="MADN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATB" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIANHAP" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="THIETBI_CTDONHAP" Member="THIETBI" ThisKey="MATB" OtherKey="MATB" Type="THIETBI" IsForeignKey="true" />
      <Association Name="DONNHAP_CTDONHAP" Member="DONNHAP" ThisKey="MADN" OtherKey="MADN" Type="DONNHAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONHANG" Member="DONHANGs">
    <Type Name="DONHANG">
      <Column Name="MADH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="HINHTHUCTT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="DONHANG_CTDONHANG" Member="CTDONHANGs" ThisKey="MADH" OtherKey="MADH" Type="CTDONHANG" />
      <Association Name="KHACHHANG_DONHANG" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="NHANVIEN_DONHANG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONNHAP" Member="DONNHAPs">
    <Type Name="DONNHAP">
      <Column Name="MADN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MACS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DONNHAP_CTDONHAP" Member="CTDONHAPs" ThisKey="MADN" OtherKey="MADN" Type="CTDONHAP" />
      <Association Name="COSO_DONNHAP" Member="COSO" ThisKey="MACS" OtherKey="MACS" Type="COSO" IsForeignKey="true" />
      <Association Name="NHACC_DONNHAP" Member="NHACC" ThisKey="MANCC" OtherKey="MANCC" Type="NHACC" IsForeignKey="true" />
      <Association Name="NHANVIEN_DONNHAP" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="KHACHHANG_DONHANG" Member="DONHANGs" ThisKey="MAKH" OtherKey="MAKH" Type="DONHANG" />
      <Association Name="KHACHHANG_TKKH" Member="TKKHs" ThisKey="MAKH" OtherKey="MAKH" Type="TKKH" />
    </Type>
  </Table>
  <Table Name="dbo.LOAITB" Member="LOAITBs">
    <Type Name="LOAITB">
      <Column Name="MALOAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="LOAITB_THIETBI" Member="THIETBIs" ThisKey="MALOAI" OtherKey="MALOAI" Type="THIETBI" />
    </Type>
  </Table>
  <Table Name="dbo.NHACC" Member="NHACCs">
    <Type Name="NHACC">
      <Column Name="MANCC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NHACC_THIETBI" Member="THIETBIs" ThisKey="MANCC" OtherKey="MANCC" Type="THIETBI" />
      <Association Name="NHACC_DONNHAP" Member="DONNHAPs" ThisKey="MANCC" OtherKey="MANCC" Type="DONNHAP" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NHANVIEN_BAOCAO" Member="BAOCAOs" ThisKey="MANV" OtherKey="MANV" Type="BAOCAO" />
      <Association Name="NHANVIEN_DONHANG" Member="DONHANGs" ThisKey="MANV" OtherKey="MANV" Type="DONHANG" />
      <Association Name="NHANVIEN_DONNHAP" Member="DONNHAPs" ThisKey="MANV" OtherKey="MANV" Type="DONNHAP" />
      <Association Name="NHANVIEN_TAIKHOANG" Member="TAIKHOANGs" ThisKey="MANV" OtherKey="MANV" Type="TAIKHOANG" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOANG" Member="TAIKHOANGs">
    <Type Name="TAIKHOANG">
      <Column Name="TENTK" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="MANV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NHANVIEN_TAIKHOANG" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TKKH" Member="TKKHs">
    <Type Name="TKKH">
      <Column Name="MaTK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MaKhau" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="KHACHHANG_TKKH" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
</Database>